[project]
name = "project"
version = "0.0.1"

dependencies = [
    "blobfile==2.0.2",
    "h5py==3.9.0",
    "imageio==2.22.1",
    "mpi4py==3.1.4",
    "numpy==1.24.4",
    "Pillow==10.0.0",
    "torch==2.0.1",
    "fastmri==0.3.0"

]

[options]
package_dir = "project"